import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const interTight = localFont({
  src: "./fonts/InterTight-VariableFont_wght.ttf",
  variable: "--font-inter-tight",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.className} antialiased bg-dark`}>
        {children}
      </body>
    </html>
  );
}
